title: Fran "d3vcho" Domínguez
description: Estudiante de Ingeniería Informática
author: Fran Domínguez
logo: /hcz-jekyll-blog/static/img/avatar.png
github: https://github.com/d3vcho
about: Freelance developer

baseurl: ""
url: "https://simplemachines.org"

allowsearch: true

disqus_shortname:
google_analytics:

share:
  twitter_username: frandominguez03
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
